#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 21 00:46:29 BRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=ComplementaryReimagined_r2.2.zip
enableShaders=false
